In [1]:
list_of_titles = ['to a T','Ashen', 'Donut County', 'Florence', 'Flower']

In [2]:
import pandas as pd
import numpy as np

In [3]:
from pymongo.mongo_client import MongoClient
from pymongo.server_api import ServerApi

uri = "mongodb+srv://dougsack:Ocana2421@cluster1.zdl0b.mongodb.net/?retryWrites=true&w=majority&appName=Cluster1"

# Create a new client and connect to the server
client = MongoClient(uri, server_api=ServerApi('1'))

# Send a ping to confirm a successful connection
try:
    client.admin.command('ping')
    print("Pinged your deployment. You successfully connected to MongoDB!")
except Exception as e:
    print(e)

db = client['ai_sales_data']
collection = db['units']

query = {"product": {"$in": list_of_titles}}
query_docs = collection.find(query)
df = pd.DataFrame(query_docs)

Pinged your deployment. You successfully connected to MongoDB!

df['unit_daily_delta']  = df.groupby('product')['units'].pct_change()
df['rev_daily_delta']  = df.groupby('product')['revenue'].pct_change()

In [4]:
df = df.groupby(["product", "weeks_from_release"], as_index=False)["cume_units"].max()
df = df.sort_values(['product', 'weeks_from_release'])

In [5]:
df['cume_units_delta'] = df.groupby('product')['cume_units'].pct_change().fillna(0)

In [6]:
norm_curve  = df.groupby('weeks_from_release')[['cume_units_delta']].mean()

In [7]:
norm_curve

                    cume_units_delta
weeks_from_release
1                           0.000000
2                           0.375197
3                           0.168177
4                           0.198621
5                           0.950547
...                              ...
378                         0.003512
379                         0.001973
380                         0.001733
381                         0.005561
382                         0.000017

[382 rows x 1 columns]

In [8]:
norm_curve.head().to_clipboard()

In [9]:
core_title = 'to a T'

In [10]:
core = df.query("product ==@core_title")

In [11]:
core_df = core.groupby('weeks_from_release')[['cume_units']].max()

In [12]:
core_df

                    cume_units
weeks_from_release
1                         5443
2                         6750
3                         7226
4                         7492
5                         7689

In [13]:
actual_df = norm_curve#.set_index('weeks_from_release')
curve_df = core#.set_index('weeks_from_release')

In [41]:
actual_df

                    cume_units_delta
weeks_from_release
1                           0.000000
2                           0.375197
3                           0.168177
4                           0.198621
5                           0.950547
...                              ...
378                         0.003512
379                         0.001973
380                         0.001733
381                         0.005561
382                         0.000017

[382 rows x 1 columns]

In [15]:
# 2. Get the last known week and value
last_week = core_df.index.max()
last_value = core_df.loc[last_week, 'cume_units']

# 3. Extract future deltas only
future_deltas = norm_curve.loc[last_week+1:]

# 4. Apply deltas forward
projected = []
current_value = last_value

for week, delta in future_deltas['cume_units_delta'].items():
    current_value = current_value * (1 + delta)
    projected.append((week, int(np.ceil(current_value))))  # ceil and cast to int

# 5. Build a DataFrame for projected values
projected_df = pd.DataFrame(projected, columns=['weeks_from_release', 'cume_units']).set_index('weeks_from_release')

# 6. Combine with actuals
full_df = pd.concat([core_df, projected_df])

In [69]:
full_df.max().values[0]

295386

In [73]:
core_df.max().values[0]

7689