https://docs.google.com/spreadsheets/d/1XNp2FBsnFsUoqwEN5b1FXloYbjMMkNc9Re8G4gVCg8U/edit?gid=0#gid=0

In [1]:
import pandas as pd
import glob
import os
import warnings

warnings.filterwarnings("ignore")

In [2]:
from pymongo import UpdateOne

## Establish connection to Account
from pymongo.mongo_client import MongoClient
from pymongo.server_api import ServerApi

uri = "mongodb+srv://dougsack:Ocana2421@cluster1.zdl0b.mongodb.net/?retryWrites=true&w=majority&appName=Cluster1"

# Create a new client and connect to the server
client = MongoClient(uri, server_api=ServerApi('1'))

# Send a ping to confirm a successful connection
try:
    client.admin.command('ping')
    print("Pinged your deployment. You successfully connected to MongoDB!")
except Exception as e:
    print(e)

Pinged your deployment. You successfully connected to MongoDB!

In [3]:
db = client['ai_sales_data']
collection = db['units']

In [4]:
docs_1st_year = collection.find({ "dar": { "$gte": 0, "$lte": 365 }, "product": { "$not": { "$regex": "Soundtrack" } } })
docs_at_launch = collection.find({ "dar": {"$eq": 0 }, "product": { "$not": { "$regex": "Soundtrack" } } })

In [5]:
docs = collection.find({ "dar": { "$gte": 0}, "product": { "$not": { "$regex": "Soundtrack" } } })

In [6]:
df = pd.DataFrame(docs)
df_first_year = pd.DataFrame(docs_1st_year)
df_launch = pd.DataFrame(docs_at_launch)

In [7]:
df = df.sort_values("day")
df_first_year = df_first_year.sort_values("day")
df_launch =df_launch.sort_values("day")

In [8]:
folder_path = "wishlists/Annapurna Interactive Historical Revenues - releases_dates.csv"
dates  = pd.read_csv(folder_path)
dates = dates.dropna(subset='pc_release_date')
dates['pc_release_date'] = pd.to_datetime(dates['pc_release_date'])
release_date_dict = dates.groupby('product')['pc_release_date'].min().to_dict()

df.query("weeks_from_release <=-12").drop_duplicates(subset='_id', keep='last')

In [9]:
len(df['product'].unique())

46

In [10]:
df.sort_values(by='dar', ascending=False).head().columns

Index(['_id', 'cume_units', 'dar', 'day', 'product', 'product_day', 'units',
       'weeks_from_release', 'cume_revs', 'revenue', 'revs_percent_of_max',
       'units_percent_of_max', 'avg_price', 'rev_daily_delta',
       'unit_daily_delta', 'release_date', 'platform_units', 'cume_wishlists',
       'wishlist_adds', 'wishlists_percent_of_max', 'wl_daily_delta',
       'cume_non_owner_visits', 'non_owner_visits_percent_of_max',
       'visits_daily_delta', 'non_owner_visits', 'cume_non_owner_impressions',
       'impressions_daily_delta', 'non_owner_impressions',
       'non_owner_impressions_percent_of_max', 'cume_free_units',
       'cume_impressions', 'cume_refunded_units', 'cume_visits',
       'cume_wishlist_adds', 'free_units', 'impressions', 'refunded_units',
       'visits'],
      dtype='object')

In [11]:
value_cols = ['cume_units', 'cume_free_units', 'cume_revs','cume_visits', 'cume_impressions','cume_wishlists']

In [12]:
df.groupby("product")[value_cols].max().sort_values('cume_units', ascending=False)

,cume_units,cume_free_units,cume_revs,cume_visits,cume_impressions,cume_wishlists
product,,,,,,
Stray,6796319.0,8526733.0,1.546259e+08,86476129.0,2.505766e+09,11271773.0
Outer Wilds,3320426.0,1521963.0,5.226657e+07,35948970.0,2.139258e+09,5175400.0
What Remains of Edith Finch,2639351.0,7383520.0,2.031659e+07,10417140.0,4.405365e+08,2761199.0
Journey,1818451.0,0.0,1.045893e+07,13785549.0,5.944810e+08,1877231.0
Donut County,1252502.0,5680.0,7.827300e+06,2736235.0,1.353933e+08,882043.0
Gorogoa,1153818.0,5649.0,6.543445e+06,4244692.0,2.049527e+08,975128.0
Outer Wilds - Echoes of the Eye DLC,1023201.0,19733.0,1.058241e+07,4071839.0,2.068626e+08,334232.0
Florence,822529.0,1585.0,2.042814e+06,3367569.0,1.164708e+08,756554.0
Storyteller,606173.0,286.0,6.916743e+06,10874729.0,3.094887e+08,1130308.0
Neon White,525321.0,3709.0,9.277689e+06,14594918.0,5.638050e+08,1358693.0
Ashen,496626.0,568859.0,1.001395e+07,4392421.0,1.190822e+08,921100.0
Flower,427498.0,22.0,9.731757e+05,2535091.0,6.726344e+07,320595.0
Twelve Minutes,405089.0,1990.0,6.581405e+06,12160639.0,3.220337e+08,1220873.0
Sayonara Wild Hearts,317595.0,395431.0,2.728686e+06,2162433.0,1.385026e+08,494245.0
Cocoon,293887.0,1779.0,4.920727e+06,9391392.0,3.312393e+08,1059181.0
The Pathless,214558.0,3057.0,5.104455e+06,3326334.0,1.152618e+08,487939.0
Outer Wilds - Archaeologist Edition BUNDLE,213178.0,10840.0,5.168834e+06,NaN,NaN,149948.0
Telling Lies,181419.0,504537.0,1.818245e+06,1469098.0,3.448729e+07,401905.0
Due Process,160082.0,0.0,2.313704e+06,1.0,1.030000e+02,310274.0
Gone Home,154322.0,NaN,1.019883e+06,NaN,NaN,NaN
Kentucky Route Zero: TV Edition,149918.0,11085.0,2.805052e+06,NaN,NaN,179112.0
Ashen - Nightstorm Isle DLC,147526.0,NaN,6.504521e+05,NaN,NaN,NaN
The Unfinished Swan,140045.0,0.0,8.078990e+05,2269836.0,9.109377e+07,261766.0
Solar Ash,121798.0,1367.0,3.251440e+06,3977212.0,9.944125e+07,436100.0
Lorelei and the Laser Eyes,113677.0,1184.0,2.382087e+06,3029769.0,7.931228e+07,436775.0
Wattam,94449.0,772.0,1.079374e+06,2094623.0,5.669388e+07,120224.0
Wanderstop,83938.0,1148.0,1.930916e+06,3326520.0,1.101640e+08,605685.0
The Artful Escape,71413.0,358707.0,8.394031e+05,2224494.0,1.005162e+08,279586.0
If Found...,68511.0,402.0,5.245197e+05,1221255.0,2.936406e+07,237687.0
Mundaun,66167.0,4060.0,8.438063e+05,2072006.0,6.424050e+07,217599.0
I Am Dead,58141.0,314500.0,6.921670e+05,1361793.0,3.002481e+07,231189.0
Lushfoil Photography Sim,49738.0,969.0,4.949618e+05,2735471.0,5.867768e+07,289745.0
Maquette,44744.0,2520981.0,5.657939e+05,1511853.0,5.778833e+07,167189.0
A Memoir Blue,37752.0,1433.0,1.928630e+05,846560.0,2.999223e+07,112744.0
Ashen Definitive Edition,36489.0,NaN,4.405885e+05,NaN,NaN,NaN
Last Stop,31086.0,278673.0,3.995283e+05,1117882.0,4.934016e+07,144782.0
Skin Deep,29961.0,0.0,5.224230e+05,1957266.0,7.270781e+07,184496.0
Open Roads,20401.0,897.0,3.347926e+05,1630009.0,3.364176e+07,219162.0
Thirsty Suitors,14353.0,12112.0,3.364443e+05,1747988.0,3.182695e+07,127377.0
Hindsight,13852.0,1214.0,1.210546e+05,681599.0,2.482636e+07,90737.0
Hohokum,12764.0,0.0,7.987052e+04,796938.0,7.756856e+07,64304.0
Wheel World,12358.0,423.0,2.188062e+05,1105360.0,3.430513e+07,157144.0
Flock,9955.0,875.0,1.760974e+05,1151791.0,2.468763e+07,106222.0
to a T,8740.0,967.0,1.463978e+05,687274.0,1.404544e+07,64736.0
Morsels,0.0,0.0,0.000000e+00,350007.0,4.654094e+06,68082.0
BattleSage,NaN,NaN,NaN,82643.0,3.016070e+05,3246.0

In [13]:
df_first_year.groupby("product")[value_cols].max().sort_values('cume_units', ascending=False)

,cume_units,cume_free_units,cume_revs,cume_visits,cume_impressions,cume_wishlists
product,,,,,,
Stray,3839538.0,8425259.0,93751545.92,62639176.0,1.495294e+09,7378822.0
Journey,560344.0,0.0,5062269.11,1932360.0,7.666782e+07,857072.0
Storyteller,458107.0,261.0,5459451.72,8591716.0,2.275887e+08,888352.0
Outer Wilds - Echoes of the Eye DLC,379912.0,3998.0,4295139.25,1647920.0,7.527879e+07,153454.0
What Remains of Edith Finch,312770.0,1270.0,4631936.27,NaN,NaN,667755.0
Neon White,299052.0,3253.0,6048116.87,10788924.0,3.910878e+08,947466.0
Twelve Minutes,236124.0,761.0,4592180.10,9465600.0,2.613727e+08,943602.0
Cocoon,226754.0,1643.0,4058952.20,8160934.0,2.539670e+08,904752.0
Outer Wilds,207300.0,765.0,4911183.32,NaN,NaN,396603.0
Gorogoa,199704.0,1975.0,1975827.35,NaN,NaN,309752.0
Donut County,191552.0,1697.0,2182842.21,NaN,NaN,290247.0
Sayonara Wild Hearts,146269.0,3230.0,1454282.05,NaN,NaN,233906.0
Due Process,135839.0,0.0,2168563.35,1.0,7.200000e+01,253568.0
The Pathless,119334.0,2673.0,3691140.00,2042314.0,6.897631e+07,227358.0
Lorelei and the Laser Eyes,100657.0,1179.0,2142446.66,2870559.0,7.426782e+07,407700.0
Wanderstop,83938.0,1148.0,1930915.96,3326520.0,1.101640e+08,605685.0
Solar Ash,83897.0,1317.0,2610330.90,3136088.0,7.684670e+07,314031.0
Kentucky Route Zero: TV Edition,76602.0,1945.0,1621611.93,NaN,NaN,75083.0
Ashen,71574.0,0.0,2563210.76,NaN,NaN,259864.0
Wattam,59384.0,763.0,841070.12,1482849.0,3.427256e+07,72324.0
Telling Lies,59150.0,687.0,875417.98,NaN,NaN,241384.0
Florence,53511.0,0.0,152719.85,NaN,NaN,NaN
Flower,50432.0,21.0,243017.57,NaN,NaN,138335.0
Lushfoil Photography Sim,49738.0,969.0,494961.81,2735471.0,5.867768e+07,289745.0
The Unfinished Swan,36134.0,0.0,328847.23,831794.0,1.035695e+07,138154.0
Mundaun,30599.0,776.0,494065.11,1271116.0,3.435498e+07,111763.0
The Artful Escape,30093.0,115994.0,451815.55,1150630.0,7.565414e+07,183351.0
Skin Deep,29961.0,0.0,522423.04,1957266.0,7.270781e+07,184496.0
Outer Wilds - Archaeologist Edition BUNDLE,29513.0,1066.0,790862.48,NaN,NaN,17857.0
If Found...,25302.0,225.0,236207.18,184836.0,4.721224e+06,118002.0
Ashen - Nightstorm Isle DLC,22822.0,NaN,181164.00,NaN,NaN,NaN
I Am Dead,22737.0,1026.0,366409.18,594135.0,9.873752e+06,121271.0
Maquette,20756.0,2520825.0,334137.62,926250.0,4.224925e+07,101841.0
Open Roads,18084.0,891.0,301598.34,1549211.0,3.228297e+07,211095.0
A Memoir Blue,16774.0,1130.0,103073.06,502540.0,2.035340e+07,72903.0
Ashen Definitive Edition,15177.0,NaN,221960.39,NaN,NaN,NaN
Last Stop,12530.0,57035.0,242259.48,597528.0,3.057187e+07,90605.0
Wheel World,12358.0,423.0,218806.18,1105360.0,3.430513e+07,157144.0
Thirsty Suitors,11195.0,12105.0,278228.08,1598978.0,2.799610e+07,116093.0
Flock,9674.0,874.0,171246.18,1142696.0,2.451689e+07,105440.0
Gone Home,8744.0,NaN,122665.59,NaN,NaN,NaN
to a T,8740.0,967.0,146397.82,687274.0,1.404544e+07,64736.0
Hindsight,6344.0,1126.0,70718.90,425256.0,1.914976e+07,68855.0
Hohokum,5819.0,0.0,43484.55,532826.0,5.911184e+07,48426.0
Morsels,0.0,0.0,0.00,350007.0,4.654094e+06,68082.0
BattleSage,NaN,NaN,NaN,82643.0,3.016070e+05,3246.0

In [14]:
df_launch.groupby("product")[value_cols].max().sort_values('cume_impressions', ascending=False)

,cume_units,cume_free_units,cume_revs,cume_visits,cume_impressions,cume_wishlists
product,,,,,,
Stray,734252.0,976982.0,16940241.75,18053532.0,195596674.0,3248875.0
Twelve Minutes,51059.0,0.0,881719.32,2320407.0,56464993.0,381116.0
Cocoon,9529.0,329.0,191347.74,592064.0,22627579.0,116814.0
Wanderstop,13554.0,138.0,305013.05,1062720.0,20753803.0,278667.0
Skin Deep,5222.0,0.0,92393.56,764199.0,18294100.0,95432.0
Neon White,20919.0,99.0,457637.10,882999.0,18155069.0,142271.0
Lushfoil Photography Sim,8064.0,71.0,81955.83,1440381.0,16321778.0,166301.0
Storyteller,10405.0,48.0,131775.70,1590429.0,15933034.0,187016.0
Wheel World,3056.0,68.0,54559.33,682316.0,15782354.0,117310.0
Open Roads,1497.0,229.0,26022.93,727283.0,13342065.0,113731.0
Thirsty Suitors,909.0,11031.0,24335.91,593922.0,9518200.0,51429.0
Flock,1065.0,37.0,19587.67,600678.0,7904231.0,59932.0
to a T,2251.0,75.0,38479.18,386557.0,6940892.0,41229.0
The Artful Escape,932.0,0.0,14116.74,150895.0,5579701.0,40882.0
Lorelei and the Laser Eyes,3604.0,119.0,88570.66,350597.0,5241928.0,53743.0
Mundaun,1057.0,52.0,20176.99,129043.0,4261082.0,17955.0
Hindsight,240.0,27.0,3116.75,99151.0,4137848.0,20941.0
Solar Ash,49282.0,1195.0,1806213.07,354728.0,3732775.0,144244.0
Maquette,2379.0,552092.0,39377.95,156884.0,3450306.0,40541.0
Outer Wilds - Echoes of the Eye DLC,52908.0,16.0,675389.51,405199.0,3100765.0,54791.0
Last Stop,659.0,74.0,14938.84,137947.0,2846219.0,33022.0
Morsels,NaN,NaN,NaN,147554.0,2346738.0,39911.0
A Memoir Blue,659.0,101.0,4543.22,81885.0,2299131.0,15349.0
Wattam,35800.0,761.0,604041.89,31260.0,1841171.0,43319.0
The Pathless,74513.0,2653.0,2701935.74,130401.0,1673443.0,54125.0
Hohokum,225.0,0.0,2030.82,21445.0,965107.0,6251.0
BattleSage,NaN,NaN,NaN,80577.0,290472.0,NaN
Ashen,2290.0,0.0,96425.17,NaN,NaN,61972.0
Ashen - Nightstorm Isle DLC,48.0,NaN,444.48,NaN,NaN,NaN
Ashen Definitive Edition,1.0,NaN,52.55,NaN,NaN,NaN
Donut County,14137.0,93.0,159189.75,NaN,NaN,34754.0
Due Process,39688.0,0.0,805699.46,NaN,NaN,116080.0
Florence,NaN,NaN,NaN,NaN,NaN,NaN
Flower,2471.0,0.0,14692.68,NaN,NaN,23371.0
Gone Home,1.0,NaN,12.79,NaN,NaN,NaN
Gorogoa,8394.0,2.0,83954.79,NaN,NaN,43433.0
I Am Dead,2482.0,76.0,44037.04,NaN,NaN,33102.0
If Found...,430.0,0.0,4614.90,NaN,NaN,17621.0
Journey,114067.0,0.0,1502360.81,NaN,NaN,173544.0
Kentucky Route Zero: TV Edition,7008.0,150.0,165148.65,NaN,NaN,11204.0
Outer Wilds,2825.0,0.0,72432.28,NaN,NaN,32534.0
Outer Wilds - Archaeologist Edition BUNDLE,69.0,0.0,2203.97,NaN,NaN,101.0
Sayonara Wild Hearts,28770.0,1179.0,362449.49,NaN,NaN,30721.0
Telling Lies,5365.0,5.0,88912.49,NaN,NaN,77818.0
The Unfinished Swan,3135.0,0.0,28506.09,NaN,NaN,27157.0
What Remains of Edith Finch,11049.0,175.0,193674.26,NaN,NaN,30151.0

In [15]:
df_launch.groupby("product")[value_cols].max().sort_values('cume_wishlists', ascending=False)

,cume_units,cume_free_units,cume_revs,cume_visits,cume_impressions,cume_wishlists
product,,,,,,
Stray,734252.0,976982.0,16940241.75,18053532.0,195596674.0,3248875.0
Twelve Minutes,51059.0,0.0,881719.32,2320407.0,56464993.0,381116.0
Wanderstop,13554.0,138.0,305013.05,1062720.0,20753803.0,278667.0
Storyteller,10405.0,48.0,131775.70,1590429.0,15933034.0,187016.0
Journey,114067.0,0.0,1502360.81,NaN,NaN,173544.0
Lushfoil Photography Sim,8064.0,71.0,81955.83,1440381.0,16321778.0,166301.0
Solar Ash,49282.0,1195.0,1806213.07,354728.0,3732775.0,144244.0
Neon White,20919.0,99.0,457637.10,882999.0,18155069.0,142271.0
Wheel World,3056.0,68.0,54559.33,682316.0,15782354.0,117310.0
Cocoon,9529.0,329.0,191347.74,592064.0,22627579.0,116814.0
Due Process,39688.0,0.0,805699.46,NaN,NaN,116080.0
Open Roads,1497.0,229.0,26022.93,727283.0,13342065.0,113731.0
Skin Deep,5222.0,0.0,92393.56,764199.0,18294100.0,95432.0
Telling Lies,5365.0,5.0,88912.49,NaN,NaN,77818.0
Ashen,2290.0,0.0,96425.17,NaN,NaN,61972.0
Flock,1065.0,37.0,19587.67,600678.0,7904231.0,59932.0
Outer Wilds - Echoes of the Eye DLC,52908.0,16.0,675389.51,405199.0,3100765.0,54791.0
The Pathless,74513.0,2653.0,2701935.74,130401.0,1673443.0,54125.0
Lorelei and the Laser Eyes,3604.0,119.0,88570.66,350597.0,5241928.0,53743.0
Thirsty Suitors,909.0,11031.0,24335.91,593922.0,9518200.0,51429.0
Gorogoa,8394.0,2.0,83954.79,NaN,NaN,43433.0
Wattam,35800.0,761.0,604041.89,31260.0,1841171.0,43319.0
to a T,2251.0,75.0,38479.18,386557.0,6940892.0,41229.0
The Artful Escape,932.0,0.0,14116.74,150895.0,5579701.0,40882.0
Maquette,2379.0,552092.0,39377.95,156884.0,3450306.0,40541.0
Morsels,NaN,NaN,NaN,147554.0,2346738.0,39911.0
Donut County,14137.0,93.0,159189.75,NaN,NaN,34754.0
I Am Dead,2482.0,76.0,44037.04,NaN,NaN,33102.0
Last Stop,659.0,74.0,14938.84,137947.0,2846219.0,33022.0
Outer Wilds,2825.0,0.0,72432.28,NaN,NaN,32534.0
Sayonara Wild Hearts,28770.0,1179.0,362449.49,NaN,NaN,30721.0
What Remains of Edith Finch,11049.0,175.0,193674.26,NaN,NaN,30151.0
The Unfinished Swan,3135.0,0.0,28506.09,NaN,NaN,27157.0
Flower,2471.0,0.0,14692.68,NaN,NaN,23371.0
Hindsight,240.0,27.0,3116.75,99151.0,4137848.0,20941.0
Mundaun,1057.0,52.0,20176.99,129043.0,4261082.0,17955.0
If Found...,430.0,0.0,4614.90,NaN,NaN,17621.0
A Memoir Blue,659.0,101.0,4543.22,81885.0,2299131.0,15349.0
Kentucky Route Zero: TV Edition,7008.0,150.0,165148.65,NaN,NaN,11204.0
Hohokum,225.0,0.0,2030.82,21445.0,965107.0,6251.0
Outer Wilds - Archaeologist Edition BUNDLE,69.0,0.0,2203.97,NaN,NaN,101.0
Ashen - Nightstorm Isle DLC,48.0,NaN,444.48,NaN,NaN,NaN
Ashen Definitive Edition,1.0,NaN,52.55,NaN,NaN,NaN
BattleSage,NaN,NaN,NaN,80577.0,290472.0,NaN
Florence,NaN,NaN,NaN,NaN,NaN,NaN
Gone Home,1.0,NaN,12.79,NaN,NaN,NaN