In [1]:
from azure.storage.blob import ContainerClient
account_name = "dlsaggregatedprodr9"
container_name = "saas-gold-direct-data-access"
sas_token = "sp=rl&st=2025-08-06T11:15:05Z&se=2026-07-31T19:30:05Z&spr=https&sv=2024-11-04&sr=d&sig=022LIiARMF6VCOJ1xaQGH6wv04Fwqh8quWp%2BzX07S7w%3D&sdd=2"
folder_path = "data/studio_id=10720/"
#folder_path = "data/studio_id=[your studio ID]/"


blob_service_url = f"https://{account_name}.blob.core.windows.net/"

container_client = ContainerClient(
    account_url=blob_service_url,
    container_name=container_name,
    credential=sas_token
)

In [2]:
blob_client = container_client.get_blob_client('data/studio_id=10720/export_fact_sales.csv')
#blob_client_wishlist = container_client.get_blob_client('data/studio_id=10720/export_fact_visibility_wishlist.csv')
#blob_client_visibility = container_client.get_blob_client('data/studio_id=10720/fact_visibility.csv')

In [3]:
import time
import pandas as pd
from io import BytesIO


t0 = time.perf_counter()
data_rev = blob_client.download_blob().readall()
#data_wl = blob_client_wishlist.download_blob().readall()
#data_vis = blob_client_visibility.download_blob().readall()

t1 = time.perf_counter()

In [4]:
df = pd.read_csv(BytesIO(data_rev))
#df_wl = pd.read_csv(BytesIO(data_wl))
#df_vis = pd.read_csv(BytesIO(data_vis))

t2 = time.perf_counter()

print(f"Download: {t1 - t0:.3f}s")
print(f"CSV parse: {t2 - t1:.3f}s")
print(f"Total: {t2 - t0:.3f}s")

Download: 74.635s
CSV parse: 5.034s
Total: 79.669s

In [5]:
df.head()

,date,unique_sku_id,base_sku_id,human_name,product_id,product_name,portal_platform_region_id,portal,store,bundle_name,...,all_units,units_sold_directly,units_returned,units_freely_distributed,units_sold_in_retail,promo_regular,base_price_local,calculated_base_price_usd,calculated_base_price_local_v2,calculated_base_price_usd_v2
0,2016-12-19,115092-steam:10720,115092,Annapurna_WRoEF Developer Comp (retail),What Remains of Edith Finch:171010:10720,What Remains of Edith Finch,171010,Steam,Steam,Direct Package Sale,...,1,0,0,0,1,regular,0.0,NaN,NaN,NaN
1,2016-12-21,115093-steam:10720,115093,Annapurna_WRoEF for Beta Testing (retail),What Remains of Edith Finch:171010:10720,What Remains of Edith Finch,171010,Steam,Steam,Direct Package Sale,...,1,0,0,0,1,regular,0.0,NaN,NaN,NaN
2,2016-12-21,115093-steam:10720,115093,Annapurna_WRoEF for Beta Testing (retail),What Remains of Edith Finch:171010:10720,What Remains of Edith Finch,171010,Steam,Steam,Direct Package Sale,...,1,0,0,0,1,regular,0.0,NaN,NaN,NaN
3,2016-12-29,115093-steam:10720,115093,Annapurna_WRoEF for Beta Testing (retail),What Remains of Edith Finch:171010:10720,What Remains of Edith Finch,171010,Steam,Steam,Direct Package Sale,...,1,0,0,0,1,regular,0.0,NaN,NaN,NaN
4,2017-01-10,115093-steam:10720,115093,Annapurna_WRoEF for Beta Testing (retail),What Remains of Edith Finch:171010:10720,What Remains of Edith Finch,171010,Steam,Steam,Direct Package Sale,...,1,0,0,0,1,regular,0.0,NaN,NaN,NaN

In [6]:
df['product_day'] = df['product_name'].astype(str) + '_' + df['date'].astype(str)

In [7]:
data = df.groupby(["date",'portal','product_name','product_day'])[['all_units','units_returned','units_freely_distributed','units_sold_in_retail','gross_revenue', 'gross_returned']].sum().sort_values(by='date',ascending=False).reset_index()

In [8]:
df.columns

Index(['date', 'unique_sku_id', 'base_sku_id', 'human_name', 'product_id',
       'product_name', 'portal_platform_region_id', 'portal', 'store',
       'bundle_name', 'country_code', 'region', 'currency_code',
       'gross_revenue', 'gross_returned', 'gross_sales', 'net_sales_approx',
       'all_units', 'units_sold_directly', 'units_returned',
       'units_freely_distributed', 'units_sold_in_retail', 'promo_regular',
       'base_price_local', 'calculated_base_price_usd',
       'calculated_base_price_local_v2', 'calculated_base_price_usd_v2',
       'product_day'],
      dtype='object')

In [9]:
data.groupby("product_name")['units_returned'].sum().sort_values(ascending=False)

product_name
Stray                          257555
Outer Wilds                    253218
Journey                        126171
What Remains of Edith Finch    110103
Storyteller                     57227
                                ...
The Lost Wild                       0
People of Note                      0
Project Insomnia                    0
REV                                 0
Morsels                             0
Name: units_returned, Length: 98, dtype: int64

In [10]:
data.groupby("product_name")['all_units'].get_group("Wheel World").sum() - data.groupby("product_name")['units_freely_distributed'].get_group("Wheel World").sum() - data.groupby("product_name")['units_sold_in_retail'].get_group("Wheel World").sum() -data.groupby("product_name")['units_returned'].get_group("Wheel World").sum()

14422

In [11]:
data.head()

,date,portal,product_name,product_day,all_units,units_returned,units_freely_distributed,units_sold_in_retail,gross_revenue,gross_returned
0,2025-09-11,Nintendo,What Remains of Edith Finch,What Remains of Edith Finch_2025-09-11,1,0,0,0,23.54,0.0
1,2025-09-11,Epic,The Unfinished Swan,The Unfinished Swan_2025-09-11,2,0,0,0,10.72,0.0
2,2025-09-11,Epic,Ashen,Ashen_2025-09-11,4,0,0,0,7.13,0.0
3,2025-09-11,Epic,Ashen - Nightstorm Isle DLC,Ashen - Nightstorm Isle DLC_2025-09-11,1,0,0,0,0.60,0.0
4,2025-09-11,Epic,Donut County,Donut County_2025-09-11,2,0,0,0,6.80,0.0

In [12]:
data['date'] = pd.to_datetime(data['date'])
#data['date_str'] = data['date'].dt.strftime("%Y-%m-%d")

In [13]:
data['units_excl_refunds'] = data['all_units'] - data['units_returned'] - data['units_freely_distributed']- data['units_sold_in_retail']
data['revenue_excl_refunds'] = data['gross_revenue'] - data['gross_returned']

In [14]:
grouped = data.groupby('product_name')

In [15]:
grouped.get_group("Wheel World")['units_returned'].sum()

876

In [16]:
stop

NameError: name 'stop' is not defined

data['date_str'] = data['date'].dt.strftime("%Y-%m-%d")

In [17]:
rename_dict = {
'date':'Date', 
'product_name':'Product', 
    'portal':'Portal',
'revenue_excl_refunds':'Revenue (excl. refunds)', 
'units_excl_refunds':'Units (excl. refunds)',
'units_freely_distributed':'Free units', 
    'adds':'Wishlist adds', 
    'non_owner_visits':'Non-owner visits',
       'non_owner_impressions':'Non-owner impressions', 
'units_returned': 'Refunded units'
    
}

In [18]:
data.rename(rename_dict, axis=1, inplace=True)
#data = data.drop_duplicates(subset=['day', 'product'])
#data['day'] = pd.to_datetime(test['day'] )
#data = data.sort_values(by='day')

data.query("Date=='2025-08-10' & Product =='Solar Ash'")

In [19]:
data[['Date', 'Product','Portal', 'Revenue (excl. refunds)', 'Units (excl. refunds)',
       'Free units', 'Refunded units']].sort_values(by='Date').query("Date=='2025-08-23' & Product =='Wheel World'")

/var/folders/vh/qvl8gx_d2m370qv72srt5r1m0000gp/T/ipykernel_81540/1691093651.py:2: FutureWarning: The behavior of 'isin' with dtype=datetime64[ns] and castable values (e.g. strings) is deprecated. In a future version, these will not be considered matching by isin. Explicitly cast to the appropriate dtype before calling isin instead.
  'Free units', 'Refunded units']].sort_values(by='Date').query("Date=='2025-08-23' & Product =='Wheel World'")

,Date,Product,Portal,Revenue (excl. refunds),Units (excl. refunds),Free units,Refunded units
3085,2025-08-23,Wheel World,Microsoft,156.78,8,0,0
3223,2025-08-23,Wheel World,PlayStation,522.82,25,3,0
3167,2025-08-23,Wheel World,Steam,792.70,42,0,5

In [20]:
export_df = data[['product_day','Date', 'Product','Portal', 'Revenue (excl. refunds)', 'Units (excl. refunds)',
       'Free units', 'Refunded units']].sort_values(by='Date')

export_df.query("Date=='2025-08-23' & Product =='Wheel World'")

/var/folders/vh/qvl8gx_d2m370qv72srt5r1m0000gp/T/ipykernel_81540/3334068915.py:4: FutureWarning: The behavior of 'isin' with dtype=datetime64[ns] and castable values (e.g. strings) is deprecated. In a future version, these will not be considered matching by isin. Explicitly cast to the appropriate dtype before calling isin instead.
  export_df.query("Date=='2025-08-23' & Product =='Wheel World'")

,product_day,Date,Product,Portal,Revenue (excl. refunds),Units (excl. refunds),Free units,Refunded units
3085,Wheel World_2025-08-23,2025-08-23,Wheel World,Microsoft,156.78,8,0,0
3223,Wheel World_2025-08-23,2025-08-23,Wheel World,PlayStation,522.82,25,3,0
3167,Wheel World_2025-08-23,2025-08-23,Wheel World,Steam,792.70,42,0,5

In [21]:
pivot_df_units = export_df.pivot(index=['product_day','Product','Date'], columns='Portal',values='Units (excl. refunds)').reset_index()
pivot_df_units

Portal,product_day,Product,Date,Apple,Epic,GOG,Google,Humble,Microsoft,Nintendo,PlayStation,Steam
0,A Memoir Blue - Original Soundtrack_2022-03-24,A Memoir Blue - Original Soundtrack,2022-03-24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,31.0
1,A Memoir Blue - Original Soundtrack_2022-03-25,A Memoir Blue - Original Soundtrack,2022-03-25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,17.0
2,A Memoir Blue - Original Soundtrack_2022-03-26,A Memoir Blue - Original Soundtrack,2022-03-26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0
3,A Memoir Blue - Original Soundtrack_2022-03-27,A Memoir Blue - Original Soundtrack,2022-03-27,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0
4,A Memoir Blue - Original Soundtrack_2022-03-28,A Memoir Blue - Original Soundtrack,2022-03-28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...
88373,to a T_2025-09-06,to a T,2025-09-06,NaN,NaN,NaN,NaN,NaN,1.0,NaN,6.0,5.0
88374,to a T_2025-09-07,to a T,2025-09-07,NaN,NaN,NaN,NaN,NaN,2.0,NaN,2.0,0.0
88375,to a T_2025-09-08,to a T,2025-09-08,NaN,1.0,NaN,NaN,NaN,2.0,NaN,2.0,4.0
88376,to a T_2025-09-09,to a T,2025-09-09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.0
88377,to a T_2025-09-10,to a T,2025-09-10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,5.0

In [22]:
pivot_df_revs = export_df.pivot(index=['product_day','Product','Date'], columns='Portal',values='Revenue (excl. refunds)').reset_index()
pivot_df_revs

Portal,product_day,Product,Date,Apple,Epic,GOG,Google,Humble,Microsoft,Nintendo,PlayStation,Steam
0,A Memoir Blue - Original Soundtrack_2022-03-24,A Memoir Blue - Original Soundtrack,2022-03-24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,117.97
1,A Memoir Blue - Original Soundtrack_2022-03-25,A Memoir Blue - Original Soundtrack,2022-03-25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,61.75
2,A Memoir Blue - Original Soundtrack_2022-03-26,A Memoir Blue - Original Soundtrack,2022-03-26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,39.70
3,A Memoir Blue - Original Soundtrack_2022-03-27,A Memoir Blue - Original Soundtrack,2022-03-27,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,46.58
4,A Memoir Blue - Original Soundtrack_2022-03-28,A Memoir Blue - Original Soundtrack,2022-03-28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18.78
...,...,...,...,...,...,...,...,...,...,...,...,...
88373,to a T_2025-09-06,to a T,2025-09-06,NaN,NaN,NaN,NaN,NaN,0.06,NaN,124.51,74.98
88374,to a T_2025-09-07,to a T,2025-09-07,NaN,NaN,NaN,NaN,NaN,35.98,NaN,43.85,0.00
88375,to a T_2025-09-08,to a T,2025-09-08,NaN,17.11,NaN,NaN,NaN,16.06,NaN,39.98,84.09
88376,to a T_2025-09-09,to a T,2025-09-09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,21.59,0.00
88377,to a T_2025-09-10,to a T,2025-09-10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,19.99,102.47

In [23]:
pivot_df_free_units = export_df.pivot(index=['product_day','Product','Date'], columns='Portal',values='Free units').reset_index()
pivot_df_free_units

Portal,product_day,Product,Date,Apple,Epic,GOG,Google,Humble,Microsoft,Nintendo,PlayStation,Steam
0,A Memoir Blue - Original Soundtrack_2022-03-24,A Memoir Blue - Original Soundtrack,2022-03-24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
1,A Memoir Blue - Original Soundtrack_2022-03-25,A Memoir Blue - Original Soundtrack,2022-03-25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
2,A Memoir Blue - Original Soundtrack_2022-03-26,A Memoir Blue - Original Soundtrack,2022-03-26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
3,A Memoir Blue - Original Soundtrack_2022-03-27,A Memoir Blue - Original Soundtrack,2022-03-27,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
4,A Memoir Blue - Original Soundtrack_2022-03-28,A Memoir Blue - Original Soundtrack,2022-03-28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
88373,to a T_2025-09-06,to a T,2025-09-06,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,0.0
88374,to a T_2025-09-07,to a T,2025-09-07,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,0.0
88375,to a T_2025-09-08,to a T,2025-09-08,NaN,0.0,NaN,NaN,NaN,0.0,NaN,0.0,0.0
88376,to a T_2025-09-09,to a T,2025-09-09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0
88377,to a T_2025-09-10,to a T,2025-09-10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0

In [24]:
stop

NameError: name 'stop' is not defined

In [27]:
# Restructure each row
unit_records = []
for _, row in pivot_df_units.iterrows():
    doc = {'_id': row['product_day'],
        "platform_units": {
            "Apple": row["Apple"],
            "Epic": row["Epic"],
            "GOG": row["GOG"],
            "Google": row["Google"],
            "Humble": row["Humble"],
            "Nintendo": row["Nintendo"],
            "PS": row["PlayStation"],
            "Steam": row["Steam"],
            "Xbox": row["Microsoft"]
        },
           
    }
    unit_records.append(doc)

In [28]:
# Restructure each row
rev_records = []
for _, row in pivot_df_revs.iterrows():
    doc = {'_id': row['product_day'],
        "platform_revs": {
            "Apple": row["Apple"],
            "Epic": row["Epic"],
            "GOG": row["GOG"],
            "Google": row["Google"],
            "Humble": row["Humble"],
            "Nintendo": row["Nintendo"],
            "PS": row["PlayStation"],
            "Steam": row["Steam"],
            "Xbox": row["Microsoft"]
        },
           
    }
    rev_records.append(doc)

In [29]:
# Restructure each row
free_records = []
for _, row in pivot_df_free_units.iterrows():
    doc = {'_id': row['product_day'],
        "platform_free_units": {
            "Apple": row["Apple"],
            "Epic": row["Epic"],
            "GOG": row["GOG"],
            "Google": row["Google"],
            "Humble": row["Humble"],
            "Nintendo": row["Nintendo"],
            "PS": row["PlayStation"],
            "Steam": row["Steam"],
            "Xbox": row["Microsoft"]
        },
           
    }
    free_records.append(doc)

In [30]:
stop

NameError: name 'stop' is not defined

In [39]:
from pymongo import UpdateOne

## Establish connection to Account
from pymongo.mongo_client import MongoClient
from pymongo.server_api import ServerApi

uri = "mongodb+srv://dougsack:Ocana2421@cluster1.zdl0b.mongodb.net/?retryWrites=true&w=majority&appName=Cluster1"

# Create a new client and connect to the server
client = MongoClient(uri, server_api=ServerApi('1'))

# Send a ping to confirm a successful connection
try:
    client.admin.command('ping')
    print("Pinged your deployment. You successfully connected to MongoDB!")
except Exception as e:
    print(e)

Pinged your deployment. You successfully connected to MongoDB!

In [40]:
from datetime import datetime
date_string = datetime.today().strftime('%Y-%m-%d')

In [41]:
db = client['ai_sales_data']
collection = db['units']

In [42]:
def batchify(data, batch_size):
    for i in range(0, len(data), batch_size):
        yield data[i:i + batch_size]

In [43]:
#####
for batch in batchify(unit_records, 4000):
    operations = [
        UpdateOne(
            {"_id": doc["_id"]},
            {"$set": doc},
            upsert=True
        ) for doc in batch
    ]
    
    result = collection.bulk_write(operations)
    print(f"Matched: {result.matched_count}, Inserted: {result.upserted_count}, Modified: {result.modified_count}")

Matched: 3999, Inserted: 1, Modified: 0
Matched: 4000, Inserted: 0, Modified: 0
Matched: 4000, Inserted: 0, Modified: 1
Matched: 4000, Inserted: 0, Modified: 1
Matched: 4000, Inserted: 0, Modified: 0
Matched: 4000, Inserted: 0, Modified: 1
Matched: 4000, Inserted: 0, Modified: 0
Matched: 4000, Inserted: 0, Modified: 1
Matched: 4000, Inserted: 0, Modified: 0
Matched: 4000, Inserted: 0, Modified: 1
Matched: 4000, Inserted: 0, Modified: 1
Matched: 4000, Inserted: 0, Modified: 1
Matched: 4000, Inserted: 0, Modified: 0
Matched: 4000, Inserted: 0, Modified: 1
Matched: 4000, Inserted: 0, Modified: 1
Matched: 4000, Inserted: 0, Modified: 1
Matched: 4000, Inserted: 0, Modified: 0
Matched: 4000, Inserted: 0, Modified: 0
Matched: 4000, Inserted: 0, Modified: 2
Matched: 4000, Inserted: 0, Modified: 1
Matched: 4000, Inserted: 0, Modified: 1
Matched: 4000, Inserted: 0, Modified: 1
Matched: 378, Inserted: 0, Modified: 0

In [44]:
#####
for batch in batchify(rev_records, 4000):
    operations = [
        UpdateOne(
            {"_id": doc["_id"]},
            {"$set": doc},
            upsert=True
        ) for doc in batch
    ]
    
    result = collection.bulk_write(operations)
    print(f"Matched: {result.matched_count}, Inserted: {result.upserted_count}, Modified: {result.modified_count}")

Matched: 4000, Inserted: 0, Modified: 580
Matched: 4000, Inserted: 0, Modified: 721
Matched: 4000, Inserted: 0, Modified: 741
Matched: 4000, Inserted: 0, Modified: 1118
Matched: 4000, Inserted: 0, Modified: 957
Matched: 4000, Inserted: 0, Modified: 450
Matched: 4000, Inserted: 0, Modified: 799
Matched: 4000, Inserted: 0, Modified: 480
Matched: 4000, Inserted: 0, Modified: 362
Matched: 4000, Inserted: 0, Modified: 732
Matched: 4000, Inserted: 0, Modified: 426
Matched: 4000, Inserted: 0, Modified: 487
Matched: 4000, Inserted: 0, Modified: 1212
Matched: 4000, Inserted: 0, Modified: 906
Matched: 4000, Inserted: 0, Modified: 971
Matched: 4000, Inserted: 0, Modified: 649
Matched: 4000, Inserted: 0, Modified: 870
Matched: 4000, Inserted: 0, Modified: 545
Matched: 4000, Inserted: 0, Modified: 682
Matched: 4000, Inserted: 0, Modified: 673
Matched: 4000, Inserted: 0, Modified: 417
Matched: 4000, Inserted: 0, Modified: 1290
Matched: 378, Inserted: 0, Modified: 39

In [45]:
#####
for batch in batchify(free_records, 4000):
    operations = [
        UpdateOne(
            {"_id": doc["_id"]},
            {"$set": doc},
            upsert=True
        ) for doc in batch
    ]
    
    result = collection.bulk_write(operations)
    print(f"Matched: {result.matched_count}, Inserted: {result.upserted_count}, Modified: {result.modified_count}")

Matched: 4000, Inserted: 0, Modified: 1
Matched: 4000, Inserted: 0, Modified: 0
Matched: 4000, Inserted: 0, Modified: 1
Matched: 4000, Inserted: 0, Modified: 1
Matched: 4000, Inserted: 0, Modified: 0
Matched: 4000, Inserted: 0, Modified: 1
Matched: 4000, Inserted: 0, Modified: 0
Matched: 4000, Inserted: 0, Modified: 1
Matched: 4000, Inserted: 0, Modified: 0
Matched: 4000, Inserted: 0, Modified: 1
Matched: 4000, Inserted: 0, Modified: 1
Matched: 4000, Inserted: 0, Modified: 1
Matched: 4000, Inserted: 0, Modified: 0
Matched: 4000, Inserted: 0, Modified: 1
Matched: 4000, Inserted: 0, Modified: 1
Matched: 4000, Inserted: 0, Modified: 1
Matched: 4000, Inserted: 0, Modified: 0
Matched: 4000, Inserted: 0, Modified: 0
Matched: 4000, Inserted: 0, Modified: 2
Matched: 4000, Inserted: 0, Modified: 1
Matched: 4000, Inserted: 0, Modified: 1
Matched: 4000, Inserted: 0, Modified: 1
Matched: 378, Inserted: 0, Modified: 0

In [46]:
client.close()